version: "3.8"

services:
  scraper:
    build: .
    ports:
      - "5001:5000"
    restart: unless-stopped
    environment:
      - FLASK_ENV=production
      - FIRECRAWL_API_KEY=fc-f9bd6b9f70cf4b379281bfce7a6d4dec